#!/usr/bin/env python3
"""Emit hand-authored tabletop puzzles for Knot Swap's group modes."""

import json
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "js" / "games" / "consume-rack-boards.js"

# The word groups are intentionally ordinary real words. The rack letters force
# later levels to be rebuilt, not merely appended to an existing word.
WORD_LEVELS = [
    (["tar", "pin"], "se"),
    (["tar", "pen"], "ca"),
    (["sea", "pin"], "tr"),
    (["cat", "rain"], "pe"),
    (["art", "plane"], "c"),
    (["rat", "pen", "mop"], "ca"),
    (["tar", "pin", "mop"], "se"),
    (["cat", "tone", "ram"], "ps"),
    (["rat", "pen", "mop", "sun"], "ca"),
    (["tar", "pin", "mop", "sun"], "ea"),
    (["cat", "rain", "mop", "sun"], "pe"),
    (["art", "plane", "mop", "sun"], "c"),
    (["rat", "pen", "mop", "sun"], "ca"),
    (["tar", "pin", "mop", "sun"], "ea"),
    (["cat", "rain", "mop", "sun"], "pe"),
    (["art", "plane", "mop", "sun"], "c"),
]

# Rummy-style tiles: suit prefix + rank. Existing groups start valid; later
# solutions require splitting and joining runs around the rack tiles.
NUMBER_LEVELS = [
    ([["R3", "B3", "G3"], ["R4", "B4", "G4"], ["R5", "B5", "G5"]], ["R6", "B6"]),
    ([["R4", "B4", "G4"], ["R5", "B5", "G5"], ["R6", "B6", "G6"]], ["R3", "B3"]),
    ([["R3", "R4", "R5"], ["R7", "R8", "R9"], ["B6", "B7", "B8"]], ["R6"]),
    ([["R4", "B4", "G4"], ["R7", "R8", "R9"]], ["R6", "R10"]),
    ([["R3", "B3", "G3"], ["R4", "B4", "G4"], ["R5", "B5", "G5"], ["R6", "B6", "G6"]], ["R7", "B7"]),
    ([["R3", "R4", "R5"], ["R7", "R8", "R9"], ["B7", "B8", "B9"]], ["R6", "B6"]),
    ([["R5", "B5", "G5"], ["R8", "R9", "R10"], ["B8", "B9", "B10"]], ["R6", "R7", "B6", "B7"]),
    ([["R2", "R3", "R4"], ["R6", "R7", "R8"], ["B2", "B3", "B4"], ["G9", "Y9", "R9"]], ["R5", "B5", "B6"]),
    ([["R4", "R5", "R6"], ["R8", "R9", "R10"], ["B4", "B5", "B6"], ["G7", "Y7", "R7"]], ["R7", "B7", "B8"]),
    ([["R3", "R4", "R5"], ["R7", "R8", "R9"], ["B3", "B4", "B5"], ["B7", "B8", "B9"]], ["R6", "B6"]),
    ([["R3", "B3", "G3"], ["R4", "B4", "G4"], ["R5", "B5", "G5"], ["R6", "B6", "G6"]], ["R7", "B7"]),
    ([["R2", "B2", "G2", "Y2"], ["R3", "B3", "G3", "Y3"], ["R4", "B4", "G4", "Y4"], ["R5", "B5", "G5", "Y5"]], ["R6", "B6"]),
    ([["R4", "R5", "R6"], ["B4", "B5", "B6"], ["G4", "G5", "G6"], ["R8", "B8", "G8"]], ["R7", "B7"]),
    ([["R5", "B5", "G5", "Y5"], ["R6", "B6", "G6", "Y6"], ["R7", "B7", "G7", "Y7"], ["R8", "B8", "G8", "Y8"]], ["R9", "B9"]),
    ([["R3", "B3", "G3"], ["R4", "B4", "G4"], ["R5", "B5", "G5"], ["R6", "B6", "G6"], ["R7", "B7", "G7"]], ["R8", "B8"]),
    ([["R4", "R5", "R6"], ["R8", "R9", "R10"], ["B4", "B5", "B6"], ["B8", "B9", "B10"], ["G7", "Y7", "R7"]], ["R7", "B7"]),
]


def main():
    def levels(rows, split_words=False):
        return [
            {"n": index + 1,
             "groups": [list(group) if split_words else group for group in groups],
             "rack": list(rack) if split_words else rack}
            for index, (groups, rack) in enumerate(rows)
        ]

    payload = {
        "words": {"levels": levels(WORD_LEVELS, split_words=True)},
        "numbers": {"levels": levels(NUMBER_LEVELS)},
    }
    OUT.write_text("// Generated by generate_consume_rack_boards.py\nconst CONSUME_RACK_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
