#!/usr/bin/env python3
"""Generate journey boards for Snoob (the sticker/bubble shooter).

Unlike Consume, Snoob needs no dictionary solver: a level is just a starting
arrangement of capsules. Difficulty comes from three knobs — how many colors,
how many rows, and the carved shape — plus a "par" shot count that drives the
star rating. Colors are laid down in short horizontal runs so the board reads
as deliberate clusters (lots of near-complete matches) rather than noise, which
keeps every level comfortably winnable.

Type indices in the output are 0..(colors-1); the game maps each to a shuffled
family face at play time, exactly like endless mode.
"""

import json
import random
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "js" / "games" / "snoob-boards.js"
COLS = 7

# Each level: (colors, rows, shape). Shape carves which columns are filled per row.
#   "full"    every column
#   "arch"    hollow bottom-center (a doorway to shoot up into)
#   "pyramid" narrowing toward the bottom
#   "diamond" narrow top and bottom, wide middle
LEVELS = [
    (3, 3, "full"),
    (3, 4, "full"),
    (4, 4, "full"),
    (4, 5, "arch"),
    (4, 5, "full"),
    (5, 5, "full"),
    (5, 6, "pyramid"),
    (5, 6, "full"),
    (6, 6, "full"),
    (6, 7, "arch"),
    (6, 7, "diamond"),
    (6, 8, "full"),
]

# How long a same-color run can be, by level. A run of length N sitting on the
# board already needs only one matching shot to clear N+1 — long runs are pre-built
# matches waiting to detonate. Early levels stay short (mostly 1s) so clearing takes
# real shots; only later levels hand out generous ready-made clusters.
RUN_CHOICES = {
    1: [1, 1, 2], 2: [1, 1, 2],
    3: [1, 2, 2], 4: [1, 2, 2, 3],
    5: [2, 2, 3], 6: [2, 2, 3],
    7: [2, 3, 3], 8: [2, 3, 3, 4],
    9: [2, 3, 4], 10: [2, 3, 4],
    11: [3, 4, 4, 5], 12: [3, 4, 5],
}


def row_mask(shape, row, rows):
    """Return the list of filled column indices for a given row."""
    all_cols = list(range(COLS))
    if shape == "full":
        return all_cols
    if shape == "arch":
        # Bottom two rows get a centered gap that widens downward.
        depth = rows - 1 - row
        if depth == 0:
            return [c for c in all_cols if c in (0, 1, COLS - 2, COLS - 1)]
        if depth == 1:
            return [c for c in all_cols if c not in (3,)]
        return all_cols
    if shape == "pyramid":
        inset = row // 2
        return all_cols[inset:COLS - inset] if inset < COLS // 2 else [COLS // 2]
    if shape == "diamond":
        mid = (rows - 1) / 2
        inset = int(abs(row - mid))
        lo, hi = inset, COLS - inset
        return all_cols[lo:hi] if lo < hi else [COLS // 2]
    return all_cols


def build_level(n, colors, rows, shape, rng):
    """Lay capsules down in same-color runs sized for this level's difficulty."""
    run_choices = RUN_CHOICES.get(n, [2, 2, 3])
    board = []
    filled = 0
    run_color = rng.randrange(colors)
    run_left = 0
    for r in range(rows):
        cols = set(row_mask(shape, r, rows))
        line = []
        for c in range(COLS):
            if c not in cols:
                line.append(None)
                continue
            if run_left <= 0:
                # Start a new run; avoid repeating the same color back to back
                # so adjacent runs stay visually distinct.
                choices = [k for k in range(colors) if k != run_color] or [run_color]
                run_color = rng.choice(choices)
                run_left = rng.choice(run_choices)
            line.append(run_color)
            run_left -= 1
            filled += 1
        board.append(line)
    # Par tracks the actual difficulty: a shot typically clears (avg run + 1)
    # capsules, so shorter runs need more shots to clear the same board.
    avg_run = sum(run_choices) / len(run_choices)
    expected_shots = filled / (avg_run + 1)
    par = max(4, round(expected_shots * 1.15))
    return {
        "n": n,
        "colors": colors,
        "rows": rows,
        "shape": shape,
        "capsules": filled,
        "par": par,
        "board": board,
    }


def main():
    rng = random.Random(20260711)
    levels = [build_level(i + 1, *spec, rng) for i, spec in enumerate(LEVELS)]
    payload = {"version": 1, "cols": COLS, "levels": levels}
    text = (
        "// Generated by generate_snoob_boards.py - do not hand-edit.\n"
        "// A level is a starting capsule layout (type indices 0..colors-1) plus a par shot count.\n"
        f"const SNOOB_DATA = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    OUT.write_text(text)
    total = sum(l["capsules"] for l in levels)
    print(f"Wrote {len(levels)} levels ({total} capsules) to {OUT}")


if __name__ == "__main__":
    main()
