#!/usr/bin/env python3
"""Generate the rack-mode board packs used by Consume."""

import json
import random
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "js" / "games" / "consume-rack-boards.js"

WORDS = [
    "cat", "dog", "sun", "map", "run", "pin", "ink", "bag", "tank", "wave",
    "mint", "star", "glow", "blue", "moon", "ship", "tree", "lamp", "game",
    "grid", "crane", "plane", "stone", "sound", "light", "spark", "candy",
    "racer", "orbit", "laser", "dream", "frost", "brick", "cloud", "space",
    "piano", "smile", "ocean", "quick", "bloom", "flame", "shiny", "magic",
]
EQUATIONS = [
    ("3+5=8", "3 + 5 = 8"), ("9-4=5", "9 - 4 = 5"), ("6+7=13", "6 + 7 = 13"),
    ("8*4=32", "8 x 4 = 32"), ("9*7=63", "9 x 7 = 63"), ("48/6=8", "48 / 6 = 8"),
    ("12+19=31", "12 + 19 = 31"), ("15-8=7", "15 - 8 = 7"),
    ("14+28=42", "14 + 28 = 42"), ("56/7=8", "56 / 7 = 8"),
    ("12*6=72", "12 x 6 = 72"), ("81/9=9", "81 / 9 = 9"),
    ("27+36=63", "27 + 36 = 63"), ("91-37=54", "91 - 37 = 54"),
    ("15*8=120", "15 x 8 = 120"), ("144/12=12", "144 / 12 = 12"),
    ("125+75=200", "125 + 75 = 200"), ("144-68=76", "144 - 68 = 76"),
    ("24*5=120", "24 x 5 = 120"), ("196/14=14", "196 / 14 = 14"),
]


def scramble_rows(rows, rng):
    positions = [(row, col) for row, text in enumerate(rows) for col, ch in enumerate(text) if ch.isalnum()]
    values = [rows[row][col] for row, col in positions]
    rotated = values[1:] + values[:1]
    out = [list(text) for text in rows]
    for (row, col), value in zip(positions, rotated):
        out[row][col] = value
    return ["".join(text) for text in out], [values[0]]


def word_levels(rng):
    levels = []
    for n in range(1, 17):
        count = 2 if n <= 4 else 3 if n <= 10 else 4
        choices = rng.sample([word for word in WORDS if len(word) <= (4 if n <= 4 else 5 if n <= 10 else 6)], count)
        current, rack = scramble_rows(choices, rng)
        levels.append({"n": n, "rows": [{"cur": c, "sol": s} for c, s in zip(current, choices)], "rack": rack, "par": sum(a != b for c, s in zip(current, choices) for a, b in zip(c, s))})
    return levels


def number_levels(rng):
    levels = []
    for n in range(1, 17):
        count = 2 if n <= 4 else 3 if n <= 10 else 4
        choices = rng.sample(EQUATIONS, count)
        current, rack = scramble_rows([raw for raw, _label in choices], rng)
        levels.append({"n": n, "rows": [{"cur": c, "sol": s, "label": label} for c, (s, label) in zip(current, choices)], "rack": rack, "par": sum(a != b for c, (s, _label) in zip(current, choices) for a, b in zip(c, s) if a.isalnum())})
    return levels


def main():
    rng = random.Random(2907)
    payload = {"words": {"levels": word_levels(rng)}, "numbers": {"levels": number_levels(rng)}}
    OUT.write_text("// Generated by generate_consume_rack_boards.py\nconst CONSUME_RACK_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
